// Generated by https://quicktype.io

export interface CV {
  experience: Experience[];
  education: Education[];
}

export interface Education {
  title: string;
  school: string;
  description: string;
}

export interface Experience {
  company: string;
  role: string;
  description: string[];
  from: string;
  to: string;
}
